export const ActionTypes = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  FETCH_LOGGED_IN_USER: "FETCH_LOGGED_IN_USER",
  CREATE_TODO: "CREATE_TODO",
  DELETE_TODOS: "DELETE_TODOS"
}
